from tkinter import *
import pyttsx3
engine=pyttsx3.init('sapi5')
voices=engine.getProperty('voices')
engine.setProperty('voice',voices[0].id)
def speak():
    audio=text1.get('1.0','end-1c')
    engine.setProperty('rate',160)
    engine.say(audio)
    engine.runAndWait()
def about_us():
    w3=Toplevel(root)
    w3.title('ABOUT US')
    w3.geometry('300x300')
    w3.resizable(False,False)
    label6=Label(w3,text='Thank you for using this app ! ,This App is made by Mohamed Abbas.This App is made for purpose of learning PYTHON programming',font=('Arial,3'),wraplength=300)
    label6.pack()
root=Tk()
root.title('TEXT TO SPEECH')
root.geometry('350x350')
root.config(background='lightblue')
root.resizable(False,False)
about=Button(root,text='i',font=('Arial',8),bg='red',fg='white',activebackground='green',command=about_us)
about.place(x=10,y=10)
label=Label(root,text='TEXT  TO  SPEECH  ENGINE',fg='white',bg='green')
label.pack(pady=10)
text1=Text(root,width=25,height=3)
text1.place(x=100,y=80)
label1=Label(root,text='Enter text:',bg='lightblue').place(x=40,y=93)
submit=Button(root,text='speak',bg='blue',fg='white',activebackground='green',command=speak)
submit.place(x=150,y=160)
root.mainloop()